insert into Languages (name, number) values ('C#', '1');
insert into Languages (name, number) values ('VB.NET', '2');
insert into Languages (name, number) values ('F#', '3');
insert into Languages (name, number) values ('Java', '4');
insert into Languages (name, number) values ('Python', '5');
insert into Languages (name, number) values ('C (gcc)', '6');
insert into Languages (name, number) values ('C++ (gcc)', '7');
insert into Languages (name, number) values ('Php', '8');
insert into Languages (name, number) values ('Pascal', '9');
insert into Languages (name, number) values ('Objective-C', '10');
insert into Languages (name, number) values ('Haskell', '11');
insert into Languages (name, number) values ('Ruby', '12');
insert into Languages (name, number) values ('Perl', '13');
insert into Languages (name, number) values ('Lua', '14');
insert into Languages (name, number) values ('Nasm', '15');
insert into Languages (name, number) values ('Sql Server', '16');
insert into Languages (name, number) values ('Javascript', '17');
insert into Languages (name, number) values ('Lisp', '18');
insert into Languages (name, number) values ('Prolog', '19');
insert into Languages (name, number) values ('Go', '20');
insert into Languages (name, number) values ('Scala', '21');
insert into Languages (name, number) values ('Scheme', '22');
insert into Languages (name, number) values ('Node.js', '23');
insert into Languages (name, number) values ('Python 3', '24');
insert into Languages (name, number) values ('Octave', '25');
insert into Languages (name, number) values ('C (clang)', '26');
insert into Languages (name, number) values ('C++ (clang)', '27');
;insert into Languages (name, number) values ('C++ (vc++)', '28');
insert into Languages (name, number) values ('C (vc)', '29');
insert into Languages (name, number) values ('D', '30');
insert into Languages (name, number) values ('R', '31');
insert into Languages (name, number) values ('Tcl', '32');
insert into Languages (name, number) values ('MySQL', '33');
insert into Languages (name, number) values ('PostgreSQL', '34');
insert into Languages (name, number) values ('Oracle', '35');
insert into Languages (name, number) values ('Swift', '37');
insert into Languages (name, number) values ('Bash', '38');
insert into Languages (name, number) values ('Ada', '39');
insert into Languages (name, number) values ('Erlang', '40');
insert into Languages (name, number) values ('Elixir', '41');
insert into Languages (name, number) values ('Ocaml', '42');
insert into Languages (name, number) values ('Kotlin', '43');
insert into Languages (name, number) values ('Brainf***', '44');
insert into Languages (name, number) values ('Fortran', '45');
insert into Languages (name, number) values ('Rust', '46');
insert into Languages (name, number) values ('Clojure', '47');